# Generated by Django 5.1.4 on 2026-09-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Bootstrap Icons class, e.g. bi-code-slash', max_length=50)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature strings, e.g. ["Responsive Design", "SEO Ready"]')),
                ('technologies', models.JSONField(blank=True, default=list, help_text='List of technology strings, e.g. ["Django", "React", "PostgreSQL"]')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='services/og/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='services_se_slug_4657d0_idx'), models.Index(fields=['is_active', 'is_featured'], name='services_se_is_acti_bfbbaa_idx')],
            },
        ),
    ]
