# Generated by Django 5.1.4 on 2026-09-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Code Yari', max_length=100)),
                ('tagline', models.CharField(default='Code. Create. Grow.', max_length=200)),
                ('alt_tagline', models.CharField(blank=True, default='Sirf code nahi, Yari ke saath solution.', max_length=300)),
                ('logo_text', models.CharField(default='</> Code Yari', max_length=50)),
                ('email', models.EmailField(default='hello@codeyari.com', max_length=254)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('phone_display', models.CharField(blank=True, default='+91 98765-43210', max_length=30)),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp number with country code', max_length=20)),
                ('address', models.TextField(blank=True, default='India')),
                ('city', models.CharField(blank=True, default='India', max_length=100)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('meta_description', models.TextField(default='Code Yari — A young digital technology team providing websites, apps, SEO, digital marketing, UI/UX, AI and automation solutions.', max_length=300)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('business_hours', models.CharField(blank=True, default='Mon–Sat, 10AM–7PM IST', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Projects Completed', max_length=100)),
                ('value', models.CharField(help_text='e.g. 50+ or 3 Years', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class, e.g. bi-check-circle', max_length=50)),
                ('note', models.CharField(blank=True, help_text='Optional footnote, e.g. (Demo Data)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Stat Item',
                'verbose_name_plural': 'Stat Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
