# Generated by Django 5.1.4 on 2026-09-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('service', models.CharField(blank=True, help_text='Which service are you interested in?', max_length=100)),
                ('budget', models.CharField(blank=True, choices=[('under_10k', 'Under ₹10,000'), ('10k_25k', '₹10,000 – ₹25,000'), ('25k_50k', '₹25,000 – ₹50,000'), ('50k_1l', '₹50,000 – ₹1,00,000'), ('1l_3l', '₹1,00,000 – ₹3,00,000'), ('above_3l', 'Above ₹3,00,000'), ('discuss', "Let's Discuss")], max_length=20)),
                ('project_type', models.CharField(blank=True, choices=[('new', 'New Project'), ('redesign', 'Redesign / Revamp'), ('maintenance', 'Maintenance / Updates'), ('consulting', 'Consulting / Strategy'), ('other', 'Other')], max_length=20)),
                ('project_description', models.TextField()),
                ('deadline', models.CharField(blank=True, help_text='e.g. ASAP, 3 months, flexible', max_length=100)),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('video_call', 'Video Call')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_discussion', 'In Discussion'), ('proposal_sent', 'Proposal Sent'), ('won', 'Won'), ('lost', 'Lost'), ('completed', 'Completed')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not shown to client)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead / Quote Request',
                'verbose_name_plural': 'Leads / Quote Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
