# Generated by Django 5.1.4 on 2026-09-12 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Portfolio Category',
                'verbose_name_plural': 'Portfolio Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('client_name', models.CharField(blank=True, help_text='Leave blank for demo/confidential projects', max_length=100)),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('technologies', models.JSONField(blank=True, default=list, help_text='e.g. ["Django", "PostgreSQL", "Bootstrap"]')),
                ('project_url', models.URLField(blank=True, help_text='Live project URL')),
                ('github_url', models.URLField(blank=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('is_demo', models.BooleanField(default=False, help_text='Mark as demo/sample project — displayed with a "Demo" badge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.portfoliocategory')),
            ],
            options={
                'verbose_name': 'Portfolio Project',
                'verbose_name_plural': 'Portfolio Projects',
                'ordering': ['-completion_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='portfolio.portfolioproject')),
            ],
            options={
                'verbose_name': 'Portfolio Image',
                'verbose_name_plural': 'Portfolio Images',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='portfolioproject',
            index=models.Index(fields=['slug'], name='portfolio_p_slug_0adcb4_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioproject',
            index=models.Index(fields=['published', 'featured'], name='portfolio_p_publish_0bd937_idx'),
        ),
    ]
